version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: messenger-postgres
    environment:
      POSTGRES_DB: chat_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup-database.sql:/docker-entrypoint-initdb.d/setup-database.sql
    restart: unless-stopped

volumes:
  postgres_data:
