spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/chat_v2}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

logging:
  level:
    org.springframework.web: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.sockjs: DEBUG

jwt:
  secret: ${JWT_SECRET:1YIbsNOQdqj6bNpDPrVz7Up8vGLkEmCGQGPf0HsGG7w=} # base64
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  crypto:
    # Сгенерируй:  openssl rand -base64 32
    keyBase64: ${CRYPTO_KEY_BASE64:1YIbsNOQdqj6bNpDPrVz7Up8vGLkEmCGQGPf0HsGG7w=}
  
  minio:
    endpoint: ${MINIO_ENDPOINT:https://s3.students.alabuga.space}
    region: ${MINIO_REGION:ru-cod-4-2}
    access-key: ${MINIO_ACCESS_KEY:bOWbfv5DHJgsq8PdzTKT}
    secret-key: ${MINIO_SECRET_KEY:O5HY8pbfdXgKTHZiW5XyfK21cGKGeYh5RPfqD3uM}
    path-style-access: true
    bucket: ${MINIO_BUCKET:alabuga-hr-chat-dev}
    max-file-size: 1073741824 # 1024 MB in bytes
